###
GET http://localhost:3000/api/jugadores
###
GET http://localhost:3000/api/jugadores/2
###
POST http://localhost:3000/api/jugadores
Content-Type: application/json

{
    "nombre": "Funes",
    "apellido": "Mori",
    "edad": 32,
    "posicion": "Defensor",
    "numero_casaca": 22,
    "equipo_id": 1,
    "foto": "foto_url"
}
###
PUT http://localhost:3000/api/jugadores/1
Content-Type: application/json

{
    "nombre": "Tony el ingeniero"
}
###
DELETE http://localhost:3000/api/jugadores/2