###
GET http://localhost:3000/api/partidos
###
GET http://localhost:3000/api/partidos/2
###
POST http://localhost:3000/api/partidos
Content-Type: application/json

{
    "equipo_local": 1,
    "equipo_visitante": 1,
    "fecha": "2025-03-10",
    "lugar": "Estadio Monumental",
    "resultado": "2-1",
    "latitud": -34.5453,
    "longitud": -58.4496
}
###
PUT http://localhost:3000/api/partidos/2
Content-Type: application/json

{
    "resultado": "3-2",
    "latitud": -34.5455
}
###
DELETE http://localhost:3000/api/partidos/2
