###
GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/users/2
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nombre": "Funes",
    "email": "funes@gmail.com",
    "password": "123456789"
}
###
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "nombre": "Tony el ingeniero"
}
###
DELETE http://localhost:3000/api/users/2